[versions]
kord = "0.8.x-SNAPSHOT"
logback = "1.4.5"
kordex = "1.5.6-forums-SNAPSHOT"
exposed = "0.41.1"

[libraries]
kord = { module = "dev.kord:kord-core", version.ref = "kord" }
kordex = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kordex" }

# Database
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }

# Logging
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
database = [
    "exposed-dao",
    "exposed-core",
    "exposed-jdbc"
]

kord = [
    "kord",
    "kordex"
]